---
  version: 1
  schedule:
    type: "simple"
    interval: "1s"
  workflow:
    collect:
      metrics:
        /intel/psutil/vm/available: {}
        /intel/psutil/vm/free: {}
        /intel/psutil/vm/used: {}
      config:
      publish:
        -
          plugin_name: "influx"
          config:
            host: "192.168.99.100"
            port: 8086
            database: "snap"
            user: admin
            password: db
